### ISSUE TITLE
Mind Expander 8.2

### ISSUE THREAD

**Issue by tquiocho** [tamucc-comp-bio-2020/classroom_repo#3]
2. Store the average girth of trees that are > 75 m tall into variable avg_girth_gr75.  Copy code and paste below

This should be height since there are not any girth values greater than 75 m "tall".

**Comment by cbird808** [comment]
the question is worded correctly.  you are being asked to calculate the average girth of trees that are > 75 tall.  Tall trees have girth.

**Comment by tquiocho** [comment]
Just realized that my bad
